<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumenttemplateVersionTable extends Doctrine_Table {


        /**
     * create new instance of FormTemplate
     * @return object FormTemplate
     */
    public static function instance() {
        return Doctrine::getTable('DocumenttemplateVersion');
    }

    /**
     * Set template inactive
     * @param int $id
     * @return true
     */
    public function setTemplateInactiveById($id) {
        Doctrine_Query::create()
            ->update('DocumenttemplateVersion dtv')
            ->set('dtv.activeversion','?',0)
            ->where('dtv.id = ?', $id)
            ->execute();
        return true;
    }

    /**
     *
     * @param int $id, id of the template
     * @return Doctrine_Collection
     */
    public function getDocumentTemplateId($id) {
        return Doctrine_Query::create()
            ->select('dtv.documenttemplate_id, dtv.version')
            ->from('DocumenttemplateVersion dtv')
            ->where('dtv.id = ?', $id)
            ->execute();
    }


}