<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumenttemplateTemplateTable extends Doctrine_Table {

    /**
     * create new instance of FormTemplate
     * @return object FormTemplate
     */
    public static function instance() {
        return Doctrine::getTable('DocumenttemplateTemplate');
    }



    /**
     * Get total sum of templates
     *
     * @return Doctrine_Collection
     */
    public function getTotalSumOfDocumentTemplates() {
        return Doctrine_Query::create()
                ->select('COUNT(*) AS anzahl')
                ->from('DocumenttemplateVersion dtv')
                ->leftJoin('dtv.DocumenttemplateTemplate dtt')
                ->where('dtt.deleted = ?', 0)
                ->andWhere('dtv.activeversion = ?', 1)
                ->execute();
    }


    
}