<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailinglistAllowedSenderTable extends Doctrine_Table {

    /**
     * create new instance of MailinglistAuthorizationSetting
     * @return object MailinglistAuthorizationSetting
     */
    public static function instance() {
        return Doctrine::getTable('MailinglistAllowedSender');
    }


}