<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailinglistUserTable extends Doctrine_Table {



    /**
     * create new instance of FormTemplate
     * @return object FormTemplate
     */
    public static function instance() {
        return Doctrine::getTable('MailinglistUser');
    }




    
    public function getAllUserBySlotId($id) {
        return Doctrine_Query::create()
           ->select('mlu.*, mlu.id as databaseId, ul.id, CONCAT(ud.firstname,\' \',ud.lastname) AS name')
           ->from('MailinglistUser mlu')
           ->leftJoin('mlu.UserLogin ul')
           ->leftJoin('ul.UserData ud')
           ->where('mlu.mailinglistslot_id = ?', $id)
           ->orderBy('mlu.position asc')
           ->groupBy('ul.id')
           ->execute();
    }

}