<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleTable extends Doctrine_Table {

    /**
     * create new instance of RoleTable
     * @return object RoleTable
     */
    public static function instance() {
        return Doctrine::getTable('Role');
    }

    /**
     * Function loads all roles
     * @param id $noDeleteId, can be set, if a role will be deleted, then role is not loaded
     * @return Doctrine_Collection
     */
    public function getAllRole($noDeleteId = '') {
        $query = Doctrine_Query::create()
                    ->select('r.*')
                    ->from('Role r')
                    ->orderBy('r.id ASC')
                    ->where('r.deleted = ?', 0);
        if($noDeleteId != '') {
            $query->andWhere('r.id != ?', $noDeleteId);
        }
        return $query->execute();
    }


}