<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowTemplateTable extends Doctrine_Table {
    /**
     *
     * create new instance of AdditionalText
     * @return object UserLoginTable
     */
    public static function instance() {
        return Doctrine::getTable('WorkflowTemplate');
    }


    public function getAllWorkflowTemplates($offset, $limit) {
        return Doctrine_Query::create()
            ->from('WorkflowTemplate wft')
            ->select('wft.*, wfv.id as activeversion_id, wfv.created_at as versioncreated_at')
            ->leftJoin('wft.WorkflowVersion wfv')
            ->where('wft.deleted = ?' ,0)
            ->andWhere('wft.isarchived = ?', 0)
            ->andWhere('wfv.activeversion = ?', 1)
            ->andWhere('wfv.workflowisstarted = ?', 1)
            ->orderBy('wft.id DESC')
            ->execute();
    }


    public function getWorkflowTemplateById($id) {
        return Doctrine_Query::create()
            ->from('WorkflowTemplate wft')
            ->select('wft.*,')
            ->where('wft.id = ?' ,$id)
            ->execute();
    }


    public function stopWorkflow($id) {
        Doctrine_Query::create()
            ->update('WorkflowTemplate wft')
            ->set('wft.isstopped','?',1)
            ->set('wft.stopped_at','?', time())
            ->where('wft.id = ?', $id)
            ->execute();
        return true;
        
    }


}