<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowTemplateTable extends Doctrine_Table {
    /**
     *
     * create new instance of AdditionalText
     * @return object UserLoginTable
     */
    public static function instance() {
        return Doctrine::getTable('WorkflowTemplate');
    }


    public function getAllWorkflowTemplates($offset, $limit) {
        return Doctrine_Query::create()
            ->from('WorkflowTemplate wft')
            ->select('wft.*, wfv.id as activeversion_id,wfv.workflowisstarted as workflowisstarted,wfv.startworkflow_at as startworkflow_at, wfv.created_at as versioncreated_at, wft.iscompleted')
            ->leftJoin('wft.WorkflowVersion wfv')
            ->where('wft.deleted = ?' ,0)
            ->andWhere('wft.isarchived = ?', 0)
            ->andWhere('wfv.activeversion = ?', 1)
            ->orderBy('wft.id DESC')
            ->execute();
    }


    public function getWorkflowTemplateById($id) {
        return Doctrine_Query::create()
            ->from('WorkflowTemplate wft')
            ->select('wft.*,')
            ->where('wft.id = ?' ,$id)
            ->execute();
    }


    public function getWorkflowTemplateByVersionId($id) {
        return Doctrine_Query::create()
            ->from('WorkflowTemplate wft')
            ->select('wft.*,')
            ->leftJoin('wft.WorkflowVersion wv')
            ->where('wv.id = ?' ,$id)
            ->execute();
    }


    public function stopWorkflow($id, $user_id) {
        Doctrine_Query::create()
            ->update('WorkflowTemplate wft')
            ->set('wft.isstopped','?',1)
            ->set('wft.stopped_at','?', time())
            ->set('wft.stopped_by','?', $user_id)
            ->where('wft.id = ?', $id)
            ->execute();
        return true;
        
    }

    public function setWorkflowFinished($id) {
        Doctrine_Query::create()
            ->update('WorkflowTemplate wft')
            ->set('wft.iscompleted','?',1)
            ->set('wft.completed_at','?', time())
            ->where('wft.id = ?', $id)
            ->execute();
        return true;
        
    }


    public function getAllToDoWorkflowTemplates($offset, $limit, $user_id) {
        return Doctrine_Query::create()
            ->from('WorkflowTemplate wft')
            ->select('wft.*, wfv.id as activeversion_id,wfv.workflowisstarted as workflowisstarted,wfv.startworkflow_at as startworkflow_at, wfv.created_at as versioncreated_at, wft.iscompleted')
            ->leftJoin('wft.WorkflowVersion wfv')
            ->leftJoin('wfv.WorkflowSlot wfs')
            ->leftJoin('wfs.WorkflowProcess wfp')
            ->leftJoin('wfp.WorkflowProcessUser wfpu')
            ->where('wft.deleted = ?' ,0)
            ->andWhere('wft.isarchived = ?', 0)
            ->andWhere('wft.isstopped = ?', 0)
            ->andWhere('wfv.activeversion = ?', 1)
            ->andWhere('wfv.workflowisstarted = ?', 1)
            ->andWhere('wfpu.user_id = ?', $user_id)
            ->andWhere('wfpu.decissionstate = ?', 'WAITING')
            ->orderBy('wft.id DESC')
            ->execute();
    }



}