<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowSlotFieldRadiogroupTable extends Doctrine_Table {


    public static function instance() {
        return Doctrine::getTable('WorkflowSlotFieldRadiogroup');
    }



    public function getAllItemsByWorkflowFieldId($id) {
        return Doctrine_Query::create()
            ->from('WorkflowSlotFieldRadiogroup wsfrg')
            ->select('wsfrg.*,')
            ->where('wsfrg.workflowslotfield_id = ?' ,$id)
            ->orderBy('wsfrg.position ASC')
            ->execute();
    }

}