<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowProcessUserTable extends Doctrine_Table {


    /**
     *
     * create new instance of AdditionalText
     * @return object UserLoginTable
     */
    public static function instance() {
        return Doctrine::getTable('WorkflowProcessUser');
    }

    
    public function skipStation($id) {
         return Doctrine_Query::create()
                ->update('WorkflowProcessUser wpu')
                ->set('wpu.dateofdecission','?',time())
                ->set('wpu.decissionstate', '?', 'SKIPPED')
                ->where('wpu.id = ?', $id)
                ->execute();

    }

    public function skipAllStation($id) {
         return Doctrine_Query::create()
                ->update('WorkflowProcessUser wpu')
                ->set('wpu.dateofdecission','?',time())
                ->set('wpu.decissionstate', '?', 'SKIPPED')
                ->where('wpu.workflowslotuser_id = ?', $id)
                ->execute();

    }

    public function getProcessUserByWorkflowSlotUserId($id) {
        return Doctrine_Query::create()
            ->select('wpu.*')
            ->from('WorkflowProcessUser wpu')
            ->where('wpu.workflowslotuser_id = ?', $id)
            ->orderBy('wpu.id ASC')
            ->execute();
    }


    public function getProcessById($id) {
        return Doctrine_Query::create()
            ->select('wpu.*')
            ->from('WorkflowProcessUser wpu')
            ->where('wpu.id = ?', $id)
            ->execute();
    }


    /**
     * Set a Process to useragent set
     *
     * @param int $id, id of the process
     * @return true
     */
    public function setProcessToUseragentSet($id) {
        Doctrine_Query::create()
            ->update('WorkflowProcessUser wpu')
            ->set('wpu.decissionstate','?','USERAGENTSET')
            ->where('wpu.id = ?', $id)
            ->execute();
        return true;
        
    }


    public function setWaitingStationToStoppedByAdmin($version_id) {
        return Doctrine_Query::create()
            ->update('WorkflowProcessUser wfpu, WorkflowProcess wfp')
            ->set('wfpu.decissionstate','?','STOPPEDBYADMIN')
            ->set('wfpu.dateofdecission','?',time())
            ->where('wfp.workflowversion_id = ?' ,$version_id)
            ->andWhere('wfpu.decissionstate = ?', 'WAITING')
            ->execute();
    }



    public function deleteWorkflowProcessUserByWorkfloSlotUserId($workflowslotuser_id) {
        Doctrine_Query::create()
            ->delete('WorkflowProcessUser')
            ->from('WorkflowProcessUser wfpu')
            ->where('wfpu.workflowslotuser_id = ?', $workflowslotuser_id)
            ->execute();
        return true;
        
    }

}