Role:
  tableName: cf_role
  columns:
    id: { type: integer, length: 10, primary: true, autoincrement: true }
    description: { type: string(100) }
    deleteable: { type: integer(1), default: 1 }
    editable: { type: integer(1), default: 1 }

Credential:
  tableName: cf_credential
  columns:
    id: { type: integer, length: 10, primary: true, autoincrement: true }
    usermodule: { type: string(100) }
    usergroup: { type: string(100) }
    userright: { type: string(100) }
  relations:
    Roles:
      foreignAlias: Credentials
      class: Role
      local: credential_id
      refClass: CredentialRole
      
CredentialRole:
   tableName: cf_credntialrole
   columns:
     role_id: { type: integer(10), primary: true }
     credential_id: { type: integer(10), primary: true }

User:
  tableName: cf_user
  columns:
    id: { type: integer, length: 10, primary: true, autoincrement: true }
    role_id: { type: integer, length: 10}
    firstname: { type: string(100) }
    lastname: { type: string(100) }
    email: { type: string(100) }
    username: { type: string(100) }
    password: { type: string(100) }
    street: { type: string(100) }
    zip: { type: string(100) }
    city: { type: string(100) }
    phone1: { type: string(100) }
    phone2: { type: string(100) }
    mobile: { type: string(100) }
    fax: { type: string(100) }
    organisation: { type: string(100) }
    department: { type: string(100) }
    burdenCenter: { type: string(100) }
    emailFormat: { type: string(100) }
    comment: { type: object }
  relations:
    Role: { class: Role, local: role_id, foreign: id, foreignType: many, type: one }

UserSetting:
  tableName: cf_usersetting
  columns:
    id: { type: integer, length: 10, primary: true, autoincrement: true }
    user_id: { type: integer, length: 10}
    menue1expand: { type: string(10), default: 'true'}
    menue2expand: { type: string(10), default: 'true'}
    menue3expand: { type: string(10), default: 'true'}
    refreshtime: { type: integer, default: 180}
    displayeditem: { type: integer, default: 25}
  relations:
    User: { class: User, local: user_id, foreign: id, foreignType: one, type: one, onDelete: CASCADE }

UserAgent:
  tableName: cf_useragent
  columns:
    id: { type: integer, length: 10, primary: true, autoincrement: true }
    user_id: { type: integer, length: 10}
    useragent_id: { type: integer, length: 10 }
    durationtype: { type: string(100) }
    durationlength: { type: string(100) }
  relations:
    User: { class: User, local: user_id, foreign: id, foreignType: many, type: one, onDelete: CASCADE }