all:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    [/djs/layout/main.js,/djs/layout/layout.js,/djs/layout/regionWest.js,/djs/layout/regionCenter.js,/djs/usermanagement/userPanel.js,/djs/usermanagement/userSearchbar.js,/djs/usermanagement/userGrid.js,/djs/usermanagement/userCreateWindow.js,/djs/usermanagement/userEditWindow.js,/djs/userrolemanagement/roleWindow.js,/djs/userrolemanagement/roleGrid.js,/djs/userrolemanagement/rolePopUpWindow.js,/djs/userrolemanagement/rolePopUpTabpanel.js,/djs/userrolemanagement/roleDeleteWindow.js,/djs/userrolemanagement/roleCRUD.js,/djs/sendmessage/sendMessageWindow.js,/djs/menuesetting/menuesettingModuleGrid.js,/djs/menuesetting/menuesettingModuleWindow.js,/djs/menuesetting/menuesettingModuleCRUD.js,/djs/menuesetting/menuesettingGroupGrid.js,/djs/menuesetting/menuesettingGroupWindow.js,/djs/menuesetting/menuesettingGroupCRUD.js,/djs/systemsetting/systemSettingWindow.js,/djs/systemsetting/databaseTab.js,/djs/systemsetting/emailTab.js,/djs/systemsetting/systemSettingCRUD.js,/djs/systemsetting/systemTab.js,/djs/systemsetting/authTab.js,/djs/additionaltext/additionTextWindow.js,/djs/additionaltext/additionalTextGrid.js,/djs/additionaltext/additionalTextPopUpWindow.js,/djs/additionaltext/additionalTextCRUD.js,/djs/additionaltext/additionalTextPopUpGrid.js,/djs/systemsetting/userTab.js,/djs/systemsetting/guiTab.js,/djs/myprofile/myProfilePanel.js,/djs/user/firstTab.js,/djs/user/secondTab.js,/djs/user/thirdTab.js,/djs/user/fourthTab.js,/djs/user/updateUser.js,/djs/user/saveUser.js]
  has_layout:     on
  layout:         layout
