all:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css,superboxselect]

  javascripts:    [superboxselect,/djs/layout/main.js,/djs/layout/layout.js,/djs/layout/regionWest.js,/djs/layout/regionCenter.js,/djs/usermanagement/userWindow.js,/djs/usermanagement/userSearchbar.js,/djs/usermanagement/addUserThirdTab.js,/djs/usermanagement/userGrid.js,/djs/usermanagement/userAddWindow.js,/djs/usermanagement/userCRUD.js,/djs/usermanagement/addUserFirstTab.js,/djs/usermanagement/addUserSecondTab.js,/djs/userrolemanagement/roleWindow.js,/djs/userrolemanagement/roleGrid.js,/djs/userrolemanagement/roleAddWindow.js,/djs/userrolemanagement/roleTabpanel.js,/djs/userrolemanagement/roleDeleteWindow.js,/djs/userrolemanagement/roleCRUD.js,/djs/sendmessage/sendMessageWindow.js,/djs/menuesetting/menuesettingModuleGrid.js,/djs/menuesetting/menuesettingModuleWindow.js,/djs/menuesetting/menuesettingModuleCRUD.js,/djs/menuesetting/menuesettingGroupGrid.js,/djs/menuesetting/menuesettingGroupWindow.js,/djs/menuesetting/menuesettingGroupCRUD.js,/djs/systemsetting/systemSettingWindow.js,/djs/systemsetting/databaseTab.js,/djs/systemsetting/emailTab.js]

  has_layout:     on
  layout:         layout
