#all:
#  propel:
#    class:          sfPropelDatabase
#    param:
#      dsn:          mysql://root:@localhost/dbname

all:
  myConnection:
    class: sfDoctrineDatabase
    param:
      dsn: mysql://root@localhost/cuteflow_dev
      encoding: utf8
      #encoding: ISO-8859-1