<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_field');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('type', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('writeprotected', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('color', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
    }

    public function setUp()
    {
        $this->hasMany('FieldTextfield', array(
             'local' => 'id',
             'foreign' => 'field_id'));

        $this->hasMany('FieldCheckbox', array(
             'local' => 'id',
             'foreign' => 'field_id'));

        $this->hasMany('FieldNumber', array(
             'local' => 'id',
             'foreign' => 'field_id'));

        $this->hasMany('FieldDate', array(
             'local' => 'id',
             'foreign' => 'field_id'));

        $this->hasMany('FieldFile', array(
             'local' => 'id',
             'foreign' => 'field_id'));

        $this->hasMany('FieldCombobox', array(
             'local' => 'id',
             'foreign' => 'field_id'));

        $this->hasMany('FieldCheckboxgroup', array(
             'local' => 'id',
             'foreign' => 'field_id'));

        $this->hasMany('FieldRadiogroup', array(
             'local' => 'id',
             'foreign' => 'field_id'));

        $this->hasMany('FieldTextarea', array(
             'local' => 'id',
             'foreign' => 'field_id'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($softdelete0);
    }
}