<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSystemConfiguration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_systemconfiguration');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('language', 'string', 20, array(
             'type' => 'string',
             'default' => 'en_US',
             'length' => '20',
             ));
        $this->hasColumn('showpositioninmail', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('allowunencryptedrequest', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('sendreceivermail', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('sendremindermail', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('visibleslots', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
    }

}