<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSlot extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_slot');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('template_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('deleted_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Template', array(
             'local' => 'template_id',
             'foreign' => 'id'));

        $this->hasMany('Field as Fields', array(
             'refClass' => 'SlotField',
             'local' => 'slot_id',
             'foreign' => 'field_id'));

        $this->hasMany('Node as Nodes', array(
             'local' => 'id',
             'foreign' => 'template_slot_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}