<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRole extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_role');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('description', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('deleteable', 'integer', 1, array(
             'type' => 'integer',
             'default' => '1',
             'length' => '1',
             ));
        $this->hasColumn('editable', 'integer', 1, array(
             'type' => 'integer',
             'default' => '1',
             'length' => '1',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Credential as Credentials', array(
             'refClass' => 'CredentialRole',
             'local' => 'role_id',
             'foreign' => 'credential_id'));

        $this->hasMany('User', array(
             'local' => 'id',
             'foreign' => 'role_id'));
    }
}