<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTrigger extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_trigger');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('trigger_type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('value', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dsn', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('sql_statement', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('needed_value', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->setSubClasses(array(
             'TriggerTime' => 
             array(
              'trigger_type' => '1',
             ),
             'TriggerDatabaseValue' => 
             array(
              'trigger_type' => '2',
             ),
             ));
    }

    public function setUp()
    {
        $this->hasMany('BreakpointEvent', array(
             'local' => 'id',
             'foreign' => 'trigger_id'));
    }
}