<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_config');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true, 'autoincrement' => true));
        $this->hasColumn('description', 'string', null, array('type' => 'string'));
        $this->hasColumn('config_key', 'string', null, array('type' => 'string'));
        $this->hasColumn('config_value', 'string', null, array('type' => 'string'));
    }

}