<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseWorkflowConfiguration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_workflowconfiguration');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('columntext', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('isactive', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('position', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
    }

}