<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBreakpointEvent extends Event
{
    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Trigger', array('local' => 'trigger_id',
                                       'foreign' => 'id'));
    }
}