<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUserConfiguration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_userconfiguration');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('role_id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('durationtype', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('durationlength', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('displayeditem', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('refreshtime', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('markyellow', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('markred', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('markorange', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('password', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('emailformat', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('emailtype', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('showcirculationinpopup', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('circulationdefaultsortcolumn', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('circulationdefaultsortdirection', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));
    }
}