<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEmailConfiguration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_emailconfiguration');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('smtphost', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('smtpuseauth', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('smtpport', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('smtpusername', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('smtppassword', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('smtpencryption', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('sendmailpath', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('systemreplyaddress', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('activetype', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
    }

}