<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAttachment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_attachment');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true, 'autoincrement' => true));
        $this->hasColumn('file_name', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('data', 'blob', null, array('type' => 'blob'));
        $this->hasColumn('revision_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('created_at', 'timestamp', null, array('type' => 'timestamp'));
        $this->hasColumn('updated_at', 'timestamp', null, array('type' => 'timestamp'));
    }

    public function setUp()
    {
        $this->hasOne('Revision', array('local' => 'revision_id',
                                        'foreign' => 'id'));

        $timestanpable0 = new Timestanpable();
        $this->actAs($timestanpable0);
    }
}