<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCredentialRole extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_credntialrole');
        $this->hasColumn('role_id', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '10',
             ));
        $this->hasColumn('credential_id', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '10',
             ));
    }

}