<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUserSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_usersetting');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('menue1expand', 'string', 10, array(
             'type' => 'string',
             'default' => 'true',
             'length' => '10',
             ));
        $this->hasColumn('menue2expand', 'string', 10, array(
             'type' => 'string',
             'default' => 'true',
             'length' => '10',
             ));
        $this->hasColumn('menue3expand', 'string', 10, array(
             'type' => 'string',
             'default' => 'true',
             'length' => '10',
             ));
        $this->hasColumn('refreshtime', 'integer', null, array(
             'type' => 'integer',
             'default' => '180',
             ));
        $this->hasColumn('displayeditem', 'integer', null, array(
             'type' => 'integer',
             'default' => '25',
             ));
    }

    public function setUp()
    {
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}