<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUserData extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_userdata');
        $this->hasColumn('user_id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             'primary' => true,
             ));
        $this->hasColumn('firstname', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('lastname', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('street', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('zip', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('city', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('country', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('phone1', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('phone2', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('mobile', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('fax', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('organisation', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('department', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('burdencenter', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('comment', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('lastaction', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        $this->hasOne('UserLogin', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('UserAgent', array(
             'local' => 'user_id',
             'foreign' => 'useragent_id'));
    }
}