<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAdditionalText extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_additionaltext');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('content', 'string', 5000, array(
             'type' => 'string',
             'length' => '5000',
             ));
        $this->hasColumn('contenttype', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('isactive', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
    }

    public function setUp()
    {
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($softdelete0);
    }
}