<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRevision extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_revision');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true, 'autoincrement' => true));
        $this->hasColumn('revision_nr', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('sent_at', 'timestamp', null, array('type' => 'timestamp'));
        $this->hasColumn('workflow_id', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('description', 'string', 4096, array('type' => 'string', 'length' => '4096'));
        $this->hasColumn('created_at', 'timestamp', null, array('type' => 'timestamp'));
        $this->hasColumn('updated_at', 'timestamp', null, array('type' => 'timestamp'));
        $this->hasColumn('deleted_at', 'timestamp', null, array('type' => 'timestamp'));
    }

    public function setUp()
    {
        $this->hasMany('FieldValue', array('local' => 'id',
                                           'foreign' => 'revision_id'));

        $this->hasMany('Attachment as Attachments', array('local' => 'id',
                                                          'foreign' => 'revision_id'));

        $this->hasMany('WorkflowProcess as WorkflowProcesses', array('local' => 'id',
                                                                     'foreign' => 'revision_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}