<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSubstituteInformation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_substitute_information');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true, 'autoincrement' => true));
        $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'length' => 4));
        $this->hasColumn('duration', 'integer', 4, array('type' => 'integer', 'length' => 4));
        $this->hasColumn('position', 'integer', 4, array('type' => 'integer', 'length' => 4));
        $this->hasColumn('created_at', 'timestamp', null, array('type' => 'timestamp'));
        $this->hasColumn('updated_at', 'timestamp', null, array('type' => 'timestamp'));
    }

    public function setUp()
    {
        $this->hasOne('User', array('local' => 'user_id',
                                    'foreign' => 'id'));

        $this->hasMany('WorkflowProcess as WorkflowProcesses', array('local' => 'id',
                                                                     'foreign' => 'substitute_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}