<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUserLogin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_userlogin');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('role_id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('username', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('password', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));

        $this->hasOne('UserData', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('UserWorkflowConfiguration', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('UserSetting', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($softdelete0);
    }
}