<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCredential extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_credential');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('usermodule', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('usergroup', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('userright', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Role as Roles', array(
             'refClass' => 'CredentialRole',
             'local' => 'credential_id',
             'foreign' => 'role_id'));
    }
}