<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseProjectUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_project_user');
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('role_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        $this->hasOne('Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));
    }
}