Attachment:
  tableName: cf_attachment
  columns:
    revision_id:
      foreignClass: Revision
      cascadeDelete: true
    path: {type: string}


Config:
  tableName: cf_config
  columns:
    description: {type: string}
    config_key: {type: string}
    config_value: {type: string}


CrossFieldSlot:
  tableName: cf_cross_field_slot
  columns:
    field_id:
      foreignClass: Field
    template_slot_id:
      foreignClass: TemplateSlot


CrossProjectUser:
  tableName: cf_cross_project_user
  columns:
    project_id:
      foreignClass: Project
    user_id:
      foreignClass: User


CrossTriggerUser:
  tableName: cf_cross_trigger_user
  columns:
    trigger_id:
      foreignClass: Trigger
    user_id:
      foreignClass: User


Event:
  tableName: cf_event
  columns:
    node_id:
      foreignClass: Node
      cascadeDelete: true
    type: {type: integer}
    action_type: {type: integer}
    position: {type: integer}


EventActionBreakpoint:
  tableName: cf_event_action_breakpoint
  columns:
    event_id:
      foreignClass: Event
      cascadeDelete: true
    trigger_type: {type: integer}


EventActionOdbc:
  tableName: cf_event_action_odbc
  columns:
    event_id:
      foreignClass: Event
      cascadeDelete: true
    dsn: {type: string}
    table_name: {type: string}


EventActionPdo:
  tableName: cf_event_action_pdo
  columns:
    event_id:
      foreignClass: Event
      cascadeDelete: true
    dsn: {type: string}
    username: {type: string}
    password: {type: string}
    connection_string: {type: string}
    table_name: {type: string}


EventActionPhp:
  tableName: cf_event_action_php
  columns:
    event_id:
      foreignClass: Event
      cascadeDelete: true
    script_url: {type: string}


EventActionValue:
  tableName: cf_event_action_value
  columns:
    event_action_id: {type: integer}
    action_key: {type: string}
    action_value: {type: string}


Field:
  tableName: cf_field
  columns:
    description: {type: string}
    default_value: {type: string}
    type: {type: integer}
    is_read_only: {type: integer}


FieldDefinition:
  tableName: cf_field_definition
  columns:
    field_id:
      foreignClass: Field
      cascadeDelete: true
    definition_value: {type: string}
    position: {type: integer}


FieldValue:
  tableName: cf_field_value
  columns:
    field_id:
      foreignClass: Field
      cascadeDelete: true
    revision_id:
      foreignClass: Revision
      cascadeDelete: true
    field_value: {type: string}


Node:
  tableName: cf_node
  columns:
    receiver_id:
      foreignClass: User
      cascadeDelete: true
    workflow_id:
      foreignClass: Workflow
      cascadeDelete: true
    template_id:
      foreignClass: Template
      cascadeDelete: true
    template_slot_id:
      foreignClass: TemplateSlot
      cascadeDelete: true
    description: {type: string}


NodeCondition:
  tableName: cf_node_condition
  columns:
    node_id:
      foreignClass: Node
      cascadeDelete: true
    destination_node_id:
      foreignClass: Node
      cascadeDelete: true
    node_condition: {type: string}


Process:
  tableName: cf_process
  columns:
    workflow_id:
      foreignClass: Workflow
      cascadeDelete: true
    revision_id:
      foreignClass: Revision
      cascadeDelete: true
    node_id:
      foreignClass: Node
      cascadeDelete: true
    user_id:
      foreignClass: User
      cascadeDelete: true
    substitute_id:
      foreignClass: User
      cascadeDelete: true
    decission_state: {type: integer}
    decission_date: {type: integer}
    start_date: {type: integer}


Project:
  tableName: cf_project
  columns:
    description: {type: string}


Revision:
  tableName: cf_revision
  columns:
    workflow_id:
      foreignClass: Workflow
      cascadeDelete: true
    description: {type: string}
    revision: {type: integer}
    created_at: {type: integer}


Template:
  tableName: cf_template
  columns:
    project_id:
      foreignClass: Project
      cascadeDelete: true
    description: {type: string}


TemplateSlot:
  tableName: cf_template_slot
  columns:
    template_id:
      foreignClass: Template
      cascadeDelete: true
    description: {type: string}


Trigger:
  tableName: cf_trigger
  columns:
    trigger_value: {type: string}


TriggerTime:
  tableName: cf_trigger_time
  columns:
    breakpoint_id:
      foreignClass: EventActionBreakpoint
      cascadeDelete: true
    time_value: {type: string}


TriggerDatabaseValue:
  tableName: cf_trigger_database_value
  columns:
    breakpoint_id:
      foreignClass: EventActionBreakpoint
      cascadeDelete: true
    trigger_id:
      foreignClass: Trigger
      cascadeDelete: true
    required_value: {type: string}


User:
  tableName: cf_user
  columns:
    project_id:
      foreignClass: Project
      cascadeDelete: true
    access_level: {type: integer}
    description: {type: string}
    username: {type: string}
    password: {type: string}
    firstname: {type: string}
    lastname: {type: string}
    email: {type: string}
    street: {type: string}
    country: {type: string}
    zipcode: {type: integer}
    city: {type: string}
    telephone1: {type: string}
    telephone2: {type: string}
    mobilephone: {type: string}
    fax: {type: string}
    organisation: {type: string}
    department: {type: string}
    cost_center: {type: string}
    userdefined1: {type: string}
    userdefined2: {type: string}
    created_at: {type: integer}
    updated_at: {type: integer}


UserFilter:
  tableName: cf_user_filter
  columns:
    user_id:
      foreignClass: User
      cascadeDelete: true
    description: {type: string}


UserFilterValue:
  tableName: cf_user_filter_value
  columns:
    user_filter_id:
      foreignClass: UserFilter
      cascadeDelete: true
    filter_key: {type: string}
    filter_value: {type: string}


UserIndex:
  tableName: cf_user_index
  columns:
    user_id:
      foreignClass: User
      cascadeDelete: true
      unique: true
    user_index: {type: string}


UserSubstitute:
  tableName: cf_user_substitute
  columns:
    user_id:
      foreignClass: User
      cascadeDelete: true
    substitute_id:
      foreignClass: User
      cascadeDelete: true
    delay: {type: integer}
    position: {type: integer}


Workflow:
  tableName: cf_workflow
  columns:
    template_id:
      foreignClass: Template
      cascadeDelete: true
    sender_id:
      foreignClass: User
      cascadeDelete: true
    description: {type: string}
    end_action: {type: integer}
    is_archived: {type: integer}
    is_deleted: {type: integer}