<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FieldComboboxTable extends Doctrine_Table {

    /**
     * create new instance of FieldComboboxTable
     * @return object FieldComboboxTable
     */
    public static function instance() {
       return Doctrine::getTable('FieldCombobox');
    }


    /**
     * Find all groups for a parent field
     * @param int $id, id of the parent field
     * @return Doctrine_Collection
     */
    public function findComboboxByFieldId($id) {
        return Doctrine_Query::create()
            ->from('FieldCombobox fcb')
            ->select('fcb.*')
            ->where('fcb.field_id = ?', $id)
            ->orderBy('fcb.position asc')
            ->execute();
    }

    public function deleteComboboxByFieldId($id) {
        Doctrine_Query::create()
            ->delete('FieldCombobox')
            ->from('FieldCombobox fcb')
            ->where('fcb.field_id = ?', $id)
            ->execute();
        return true;
    }

}