<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FieldTextareaTable extends Doctrine_Table {
    /**
     *
     * create new instance of FieldTextareaTable
     * @return object FieldTextareaTable
     */
    public static function instance() {
        return Doctrine::getTable('FieldTextarea');
    }

    public function updateFieldTextareaById($id, $data) {
        Doctrine_Query::create()
            ->update('FieldTextarea fta')
            ->set('fta.contenttype','?', $data['fieldTextarea_contenttype'])
            ->set('fta.content','?',$data['fieldTextarea_content'])
            ->where('fta.field_id = ?',$id)
            ->execute();
        return true;
    }


}