<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FieldNumberTable extends Doctrine_Table {
    /**
     *
     * create new instance of FieldNumber
     * @return object FieldNumber
     */
    public static function instance() {
        return Doctrine::getTable('FieldNumber');
    }

    
    public function updateFieldNumberById($id, $data) {
        Doctrine_Query::create()
            ->update('FieldNumber fn')
            ->set('fn.defaultvalue','?', $data['fieldNumber_standard'])
            ->set('fn.regex','?',$data['fieldNumber_regularexpression'])
            ->set('fn.comboboxvalue','?',$data['fieldNumber_regularexpressioncombo'])
            ->where('fn.field_id = ?',$id)
            ->execute();
        return true;
    }

}