<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FieldFileTable extends Doctrine_Table {
    /**
     * 
     * create new instance of FieldRadiogroupTable
     * @return object FieldRadiogroupTable
     */
    public static function instance() {
       return Doctrine::getTable('FieldFile');
    }


    public function updateFieldFileById($id, $data) {
        Doctrine_Query::create()
            ->update('FieldFile ff')
            ->set('ff.regex','?',$data['fieldFile_regularexpression'])
            ->where('ff.field_id = ?',$id)
            ->execute();
        return true;
    }
}