<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FieldTable extends Doctrine_Table {

    
    /**
     *
     * create new instance of FieldTable
     * @return object FieldTable
     */
    public static function instance() {
        return Doctrine::getTable('Field');
    }

    /**
     * Load all records
     * @return Doctrine_Collection
     */
    public function getAllFields() {
        return Doctrine_Query::create()
            ->from('Field f')
            ->select('f.*')
            ->orderBy('f.id DESC')
            ->where('f.deleted = ?' ,0)
            ->execute();
    }


    /**
     *
     * @param int $id, id of record to delete
     * @return true
     */
    public function deleteField($id) {
        Doctrine_Query::create()
            ->update('Field f')
            ->set('f.deleted','?',1)
            ->where('f.id = ?',$id)
            ->execute();
        return true;
    }


}