<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FieldCheckboxgroupTable extends Doctrine_Table {

    /**
     * create new instance of FieldCheckboxgroupTable
     * @return object FieldCheckboxgroupTable
     */
    public static function instance() {
       return Doctrine::getTable('FieldCheckboxgroup');
    }


    /**
     * Find all groups for a parent field
     * @param int $id, id of the parent field
     * @return Doctrine_Collection
     */
    public function findCheckboxgroupByFieldId($id) {
        return Doctrine_Query::create()
            ->from('FieldCheckboxgroup fcg')
            ->select('fcg.*')
            ->where('fcg.field_id = ?', $id)
            ->orderBy('fcg.position asc')
            ->execute();
    }


    /**
     * Delete Checkboxgroup according to its parent id
     * @param int $id, id of Checkboxgroup to delete
     * @return true
     */
    public function deleteCheckboxgroupByFieldId($id) {
        Doctrine_Query::create()
            ->delete('FieldCheckboxgroup')
            ->from('FieldCheckboxgroup fcg')
            ->where('fcg.field_id = ?', $id)
            ->execute();
        return true;
    }


}