<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormSlotTable extends Doctrine_Table {


    /**
     * create new instance of FormSlot
     * @return object FormSlot
     */
    public static function instance() {
        return Doctrine::getTable('FormSlot');
    }

    /**
     * Deletes slots by template id
     * 
     * @param int $id, template id
     * @return true
     */
    public function deleteFormSlotByTemplateId($id) {
        Doctrine_Query::create()
            ->delete('FormSlot')
            ->from ('FormSlot fs')
            ->where('fs.formtemplate_id = ?', $id)
            ->execute();

        return true;
    }


    /**
     *
     * @param array $data, items to delete
     * @return true
     */
    public function deleteFormSlotById(array $data) {
        Doctrine_Query::create()
            ->delete('FormSlot')
            ->from ('FormSlot fs')
            ->whereIn('fs.id', $data)
            ->execute();
         return true;

    }

    /**
     * Deletes slots
     * @param array $ids, ids of slot to delete
     * @return true
     */
    public function deleteSlotByArray(array $ids) {
        Doctrine::getTable('FormSlot')
                ->createQuery('fs')
                ->whereIn('fs.id', $ids)
                ->execute()
                ->delete();
        return true;
    }




}