<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormFieldTable extends Doctrine_Table {

    /**
     * create new instance of FormTemplate
     * @return object FormTemplate
     */
    public static function instance() {
        return Doctrine::getTable('FormField');
    }


    /**
     * Load FormField by its ID
     * @param int $id, id of slot
     * @return Doctrine_Collection
     */
    public function getFormFieldBySlotId($id) {
        return Doctrine_Query::create()
            ->select('ff.*')
            ->from('FormField ff')
            ->where('ff.formslot_id = ?',$id)
            ->orderBy('ff.position asc')
            ->execute();
    }


    /**
     * Delete Fields by the id of its parent template
     * @param int $id, id of template
     * @return true
     */
    public function deleteFormFieldByTemplateId($id) {
        Doctrine_Query::create()
            ->delete('FormField')
            ->from ('FormField ff')
            ->where('ff.formtemplate_id = ?', $id)
            ->execute();
    }

}