<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormFieldTable extends Doctrine_Table {

    /**
     * create new instance of FormTemplate
     * @return object FormTemplate
     */
    public static function instance() {
        return Doctrine::getTable('FormField');
    }


    /**
     * Load FormField by its ID
     * @param int $id, id of slot
     * @return Doctrine_Collection
     */
    public function getFormFieldBySlotId($id) {
        return Doctrine_Query::create()
            ->select('ff.*')
            ->from('FormField ff')
            ->where('ff.formslot_id = ?',$id)
            ->orderBy('ff.position asc')
            ->execute();
    }


    /**
     * Delete Fields by the id of its parent template
     * @param int $id, id of template
     * @return true
     */
    public function deleteFormFieldByTemplateId($id) {
        Doctrine_Query::create()
            ->delete('FormField')
            ->from ('FormField ff')
            ->where('ff.formtemplate_id = ?', $id)
            ->execute();
        return true;
    }


    /**
     *
     * @param array $data, id's to delete
     * @return true
     */
    public function deleteFieldBySlotId(array $data) {
       Doctrine_Query::create()
            ->delete('FormField')
            ->from ('FormField ff')
            ->whereIn('ff.formslot_id', $data)
            ->execute();
        return true;
    }

    /**
     * Delete FormFields by Id
     * @param array $data, ids to delete
     * @return true
     */
    public function deleteFieldById(array $data) {
       Doctrine_Query::create()
            ->delete('FormField')
            ->from ('FormField ff')
            ->whereIn('ff.id', $data)
            ->execute();
        return true;
    }


    /**
     * Delete fields by an array of slot ids
     * @param array $ids, slot ids in array
     * @return true
     */
    public function deleteFieldBySlotIdInArray(array $ids) {
        Doctrine::getTable('FormField')
                ->createQuery('ff')
                ->whereIn('ff.formslot_id', $ids)
                ->execute()
                ->delete();
        return true;
    }


    /**
     * Delete fields by its id
     * @param array $ids, array of ids to delete
     * @return true
     */
    public function deleteFieldByIdInArray (array $ids) {
         Doctrine::getTable('FormField')
                ->createQuery('ff')
                ->whereIn('ff.id', $ids)
                ->execute()
                 ->delete();
        return true;
    }

}