<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailinglistAllowedSenderTable extends Doctrine_Table {

    /**
     * create new instance of MailinglistAuthorizationSetting
     * @return object MailinglistAuthorizationSetting
     */
    public static function instance() {
        return Doctrine::getTable('MailinglistAllowedSender');
    }


    /**
     * ID of the users
     * @param int $id
     * @return Doctrine_Collection
     */
    public function getAllowedSenderById($id) {
        return Doctrine_Query::create()
               ->select('mlas.*, mlas.id as databaseId, ul.id, CONCAT(ud.firstname,\' \',ud.lastname) AS name')
               ->from('MailinglistAllowedSender mlas')
               ->leftJoin('mlas.UserLogin ul')
               ->leftJoin('ul.UserData ud')
               ->where('mlas.mailinglisttemplate_id = ?', $id)
               ->orderBy('mlas.position asc')
               ->groupBy('ul.id')
               ->execute();
    }

}