<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailinglistAuthorizationSettingTable extends Doctrine_Table {

    /**
     * create new instance of MailinglistAuthorizationSetting
     * @return object MailinglistAuthorizationSetting
     */
    public static function instance() {
        return Doctrine::getTable('MailinglistAuthorizationSetting');
    }



    /**
     * Update table items for AuthorizationConfiguration
     * @param int $id, id of the row to update
     * @param string $column, column of the tablerow which is to update
     * @return true;
     */
    public function updateAuthorizationConfigurationById($id, $value, $column) {
        Doctrine_Query::create()
            ->update('MailinglistAuthorizationSetting mas')
            ->set('mas.'.$column,'?', 1)
            ->where ('mas.mailinglisttemplate_id = ?',$id)
            ->andWhere('mas.type = ?', $value)
            ->execute();
        return true;
    }


}