<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SystemConfigurationTable extends Doctrine_Table {

    /**
     * create new instance of SystemConfigurationTable
     * @return object SystemConfigurationTable
     */
    public static function instance() {
        return Doctrine::getTable('SystemConfiguration');
    }

    /**
     * Loads System config
     * @return Doctrine_Collection
     */
    public function getSystemConfiguration() {
        return Doctrine_Query::create()
                ->select('sc.*')
                ->from('SystemConfiguration sc')
                ->execute();
    }

    /**
     * Update system configuration
     * @param array $data
     * @return <type>
     */
    public function updateSystemConfiguration (array $data) {
        Doctrine_Query::create()
            ->update('SystemConfiguration sc')
            ->set('sc.language','?',$data['systemsetting_language'])
            ->set('sc.showpositioninmail','?',$data['systemsetting_showposition'])
            ->set('sc.sendreceivermail','?',$data['systemsetting_sendreceivermail'])
            ->set('sc.sendremindermail','?',$data['systemsetting_sendremindermail'])
            ->set('sc.visibleslots','?',$data['systemsetting_slotvisible'])
            ->where ('sc.id = ?',1)
            ->execute();
        return true;
    }

}