<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserAgentTable extends Doctrine_Table {
    /**
     * 
     * create new instance of UserAgentTable
     * @return object UserAgentTable
     */
    public static function instance() {
        return Doctrine::getTable('UserAgent');
    }

    /**
     * Loads all user agents for a specific userid
     * @param int $id, useragents for user
     * @return Doctrine_Collection
     */
    public function getAllUserAgentForSingleUser($id) {
        return Doctrine_Query::create()
            ->select('ua.*')
            ->from('UserAgent ua')
            ->where('ua.user_id = ?', $id)
            ->leftJoin('ua.UserData ud')
            ->leftJoin('ud.UserLogin ul')
            ->orderBy('ua.position asc')
            ->where('ul.deleted = ?', 0)
            ->execute();
    }

    /**
     * Deletes all useragents for a specific id
     * @param int $user_id, user_id
     * @return true;
     */
    public function deleteAllUserAgentForId($data, $user_id) {
        Doctrine_Query::create()
            ->delete('UserAgent')
            ->from('UserAgent ua')
            ->where('ua.user_id = ?',$user_id)
            ->execute();
        return true;
    }
}