<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowSlotFieldCombobxTable extends Doctrine_Table {


    public static function instance() {
        return Doctrine::getTable('WorkflowSlotFieldCombobx');
    }



    public function getAllItemsByWorkflowFieldId($id) {
        return Doctrine_Query::create()
            ->from('WorkflowSlotFieldCombobx wsfc')
            ->select('wsfc.*,')
            ->where('wsfc.workflowslotfield_id = ?' ,$id)
            ->orderBy('wsfc.position ASC')
            ->execute();
    }

}