<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowSlotFieldCheckboxgroupTable extends Doctrine_Table {



    public static function instance() {
        return Doctrine::getTable('WorkflowSlotFieldCheckboxgroup');
    }



    public function getAllItemsByWorkflowFieldId($id) {
        return Doctrine_Query::create()
            ->from('WorkflowSlotFieldCheckboxgroup wsfcg')
            ->select('wsfcg.*,')
            ->where('wsfcg.workflowslotfield_id = ?' ,$id)
            ->orderBy('wsfcg.position ASC')
            ->execute();
    }

}