<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowSlotFieldTextfieldTable extends Doctrine_Table {

    public static function instance() {
        return Doctrine::getTable('WorkflowSlotFieldTextfield');
    }



    public function getAllItemsByWorkflowFieldId($id) {
        return Doctrine_Query::create()
            ->from('WorkflowSlotFieldTextfield wsft')
            ->select('wsft.*,')
            ->where('wsft.workflowslotfield_id = ?' ,$id)
            ->execute();
    }

}