<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowSlotTable extends Doctrine_Table {
     /**
      * 
     * create new instance of FormTemplate
     * @return object FormTemplate
     */
    public static function instance() {
        return Doctrine::getTable('WorkflowSlot');
    }

    /**
     *
     * Get the first Slot of a new Workflow
     *
     * @param int $version_id, current version
     * @param int $template_id, current template
     * @return Doctrine_Collection
     */
    public function getFirstSlotOfNewCirculation($version_id, $template_id) {
        return Doctrine_Query::create()
            ->select('wfs.*')
            ->from('WorkflowSlot wfs')
            ->leftJoin('wfs.WorkflowVersion wfv')
            ->where('wfv.id = ?', $version_id)
            ->andWhere('wfv.workflowtemplate_id = ?', $template_id)
            ->orderBy('wfs.position ASC')
            ->execute();
    }

}